In [1]:
import numpy as np

In [9]:
#initialising 1d array of int type
a=np.array([1,2,3,4],dtype='int16')
print(a)

[1 2 3 4]


In [3]:
#initialising 2d array of float type
b=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0],[6.0,7.0,8.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]
 [6. 7. 8.]]


In [4]:
# get dimension
print(a.ndim)
print(b.ndim)

1
2


In [5]:
# get shape
print(a.shape)
print(b.shape)

(4,)
(3, 3)


In [6]:
 # get type
print(a.dtype)
print(b.dtype)

int16
float64


In [7]:
# get size
print(a.itemsize)            
print(b.itemsize)            

2
8


In [8]:
# size
print(a.size)
print(b.size)

4
9


In [9]:
# total size
print(a.nbytes)
print(b.nbytes)

8
72


# Accessing/changing specific elements, row

In [10]:
a1=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a1)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# get specific element
print(a1[1,5])
print(a1[1,])
print(a1[0,3])
print(a1[1,-2])


13
[ 8  9 10 11 12 13 14]
4
13


In [12]:
# get specific row
print(a1[0, :])

[1 2 3 4 5 6 7]


In [13]:
# get specific column
print(a1[:,2])

[ 3 10]


In [14]:
# getting little more fancy [startindex:endindex:stepindex]
print(a1[0,1:7:2])

[2 4 6]


In [18]:
# changing element
a[1]=20
print(a)

a[:,3]=10
print(a)

a[:]=[15,16]
print(a)

[ 1 20  3  4]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [19]:
# 3d example
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# getting element in 3d array
print(b[1,0,0])
print(b[1,0,:])
print(b[:,1,:])

5
[5 6]
[[3 4]
 [7 8]]


In [21]:
print(b.shape)

(2, 2, 2)


In [22]:
# replace
b[1,:,:]=[[12,13],[14,15]]
print(b)

[[[ 1  2]
  [ 3  4]]

 [[12 13]
  [14 15]]]


# initialising different types of array

In [23]:
import numpy as np

In [24]:
#all 0's matrix
np.zeros((2,3))           # np.zeros(here give the shape or dimension)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.zeros(3)

array([0., 0., 0.])

In [26]:
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [27]:
# all 1's matrix
np.ones((1,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [28]:
# any other number matrix
np.full((2,2),91)        # take two values one is shape and another is the req. number

array([[91, 91],
       [91, 91]])

In [29]:
a=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(a)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [30]:
np.full(a.shape,8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [31]:
#full_like
np.full_like(a,4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [32]:
# random decimal numbers
np.random.rand(2,3)

array([[0.66248895, 0.68292141, 0.93393228],
       [0.56337489, 0.43060765, 0.78501894]])

In [33]:
# for using another array shape
np.random.random_sample(a.shape)

array([[0.63864308, 0.86764944, 0.37663755, 0.92891226, 0.4255383 ],
       [0.18760488, 0.1412713 , 0.91427804, 0.28685469, 0.70533806]])

In [34]:
# random integer numbers
np.random.randint(100,size=(2,2))

array([[ 6, 19],
       [70, 83]])

In [35]:
 np.random.randint(20,100,size=(2,2))

array([[58, 26],
       [57, 86]])

In [36]:
# identity matrix
np.identity(4)       # only one number as identity is always is a square matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
# repeat an array 
arr=np.array([[1,2,3]])
r1=np.repeat(arr,4,axis=0)      #(arrayname,no.of times to repeat,axis=0 and 1)
print(r1)                       # by default - axis -1

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [38]:
r2=np.repeat(arr,5,axis=1)
print(r2)

[[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3]]


In [39]:
out=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
out[1:4,1:4]=z
print(out)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


 # be careful when copying 

In [40]:
import numpy as np

In [41]:
a=np.array([1,2,3])
b=a.copy()             # .copy() should be used otherwise changing of value of b will change the value of a as well
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


# basic maths

In [42]:
import numpy as np

In [43]:
a=np.array([1,2,3,4])

In [44]:
a+2

array([3, 4, 5, 6])

In [45]:
a-2

array([-1,  0,  1,  2])

In [46]:
a**3


array([ 1,  8, 27, 64])

In [47]:
b=np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [48]:
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [49]:
print(np.sin(b))

[-0.95892427 -0.2794155   0.6569866   0.98935825]


# linear algebra

In [50]:
import numpy as np

In [51]:
a=np.ones((2,3))
b=np.full((3,2),2)
print(np.matmul(a,b))

[[6. 6.]
 [6. 6.]]


In [52]:
# finding the determinant

c=np.identity(3)
print(np.linalg.det(c))

1.0


# statistics

In [2]:
stats=np.array([[1,2,3,4],[5,6,7,8]])
print(stats)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
print(stats.max())

8


In [54]:
print(np.min(stats))

1


In [55]:
print(np.max(stats))

8


In [56]:
 print(np.max(stats,axis=1))

[4 8]


In [76]:
print(np.max(stats,axis=0))

[5 6 7 8]


In [57]:
print(np.sum(stats))

36


In [58]:
print(np.sum(stats,axis=0))

[ 6  8 10 12]


In [59]:
print(np.sum(stats,axis=1))

[10 26]


In [77]:
# axis = 0 means rows me khelna and answer will have an array of number of columns
# axis = 1 means columns me khelna and answer will have an array of number of rows

# reorganizing arrays

In [60]:
import numpy as np

In [61]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [62]:
# vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
print(np.vstack((v1,v2)))
print(np.vstack([v1,v2,v2,v2]))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


In [63]:
# horizontal stack
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
print(np.hstack((v1,v1)))

[1 2 3 4 1 2 3 4]


# loading data from another file


In [64]:
import numpy as np


In [65]:
# to load data from another text file
a=np.genfromtxt("data.txt",delimiter=" ;")  #delimiter is like a seperator

a.astype('int32')            # for converting the data type


OSError: data.txt not found.

# # basic practice questions


In [66]:
# array with all zeros
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [67]:
# array with all ones
a=np.ones((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [68]:
import numpy as np
# make. 1 1 1 1 1 
#       1 0 0 0 1
#       1 0 3 0 1
#       1 0 0 0 1
#       1 1 1 1 1
a=np.ones((5,5))
b=np.zeros((3,3))
b[1,1]=3
a[1:4,1:4]=b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 3. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [69]:
a=np.array([[3,4,2,1],[7,8,6,9]])
print(np.max(a,axis=0))

[7 8 6 9]


In [70]:
print(np.min(a,axis=1))

[1 6]


In [71]:
print(np.sum(a))

40


In [72]:
print(np.mean(a))

5.0


In [73]:
print(np.median(a))

5.0


In [74]:
print(np.sum(a))

40


In [75]:
print(np.mod(a,3))   # gives th remainder 

[[0 1 2 1]
 [1 2 0 0]]


In [3]:
import numpy as np
out=np.ones((3,4))
z=3*out
print(z)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [3]:
a = np.ones((4,4))
b = a.reshape((2,8))
print(a)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
