In [2]:
import numpy as np

In [3]:
type(np.array([1,2,4,4,5]))

numpy.ndarray

In [4]:
type(np.array([1,2,3+4j,"Abhi"]))

numpy.ndarray

In [5]:
np.array([1,2,3+4j,"Abhi"])

array(['1', '2', '(3+4j)', 'Abhi'], dtype='<U64')

In [6]:
np.array([1,2,3,4.5])  # try to change all the data in float values

array([1. , 2. , 3. , 4.5])

In [7]:
np.array([[1,23,3],[2,3]]) # gives the list when elements are not proper

<ipython-input-7-c526941d6c45>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[1,23,3],[2,3]])


array([list([1, 23, 3]), list([2, 3])], dtype=object)

In [14]:
np.array([[[1,2,3],[1,2,3]],[[4,5,6],[7,8,9]]])

array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [7, 8, 9]]])

In [16]:
np.array([1,2,3],ndmin = 3) #giving the dimensions to data

array([[[1, 2, 3]]])

In [17]:
np.array([1,2,3] , dtype = complex)# typecasting

array([1.+0.j, 2.+0.j, 3.+0.j])

In [18]:
np.array([(1,2), (4,5)]) # same as previous outcome

array([[1, 2],
       [4, 5]])

In [21]:
arr = np.array([(1,2), (4,5)],dtype = [('a','<i2'),('b','<i8')])

In [22]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [23]:
type(arr[0][0])

numpy.int16

In [24]:
type(arr[0][1])

numpy.int64

In [26]:
# in previous example a represents 1 and 4 ,b represents 2 and 5
# i<2 is the integer 16
# i<8 is the integer 64
# this is just representation

In [27]:
arr = np.array([[1,3],[1,4]])

In [28]:
arr

array([[1, 3],
       [1, 4]])

In [29]:
arr[0]

array([1, 3])

In [30]:
arr[0][1]

3

In [36]:
mat = np.mat(arr)

In [32]:
l = [23,234,56,43,90]

In [33]:
np.array(l)

array([ 23, 234,  56,  43,  90])

In [34]:
np.asarray(l)

array([ 23, 234,  56,  43,  90])

In [35]:
np.asanyarray(l)

array([ 23, 234,  56,  43,  90])

In [37]:
np.asanyarray(mat) # matrix is a type of array so it is not converted

matrix([[1, 3],
        [1, 4]])

In [38]:
issubclass(np.matrix,np.ndarray)

True

In [39]:
a = arr  # shalow copy

In [40]:
b = np.copy(arr)   # deep copy

In [41]:
arr[0][0] = 67

In [42]:
arr

array([[67,  3],
       [ 1,  4]])

In [43]:
a

array([[67,  3],
       [ 1,  4]])

In [44]:
b

array([[1, 3],
       [1, 4]])

In [45]:
arr[0:10]

array([[67,  3],
       [ 1,  4]])

In [46]:
arr[-1]

array([1, 4])

In [47]:
arr[-1:]

array([[1, 4]])

In [49]:
for i  in arr:
    print(i)

[67  3]
[1 4]


In [50]:
np.fromfunction(lambda i,j : i==j,(4,4)) # size if the array in breacket

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [3]:
np.fromfunction(lambda i,j : i*j,(4,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.],
       [0., 3., 6.]])

In [4]:
np.fromfunction(lambda i,j : i / j,(3,3))

<ipython-input-4-f56fc2f73f5f>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j : i / j,(3,3))
<ipython-input-4-f56fc2f73f5f>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j : i / j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [11]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [12]:
gen = (i*i for i in range(5))

In [13]:
gen

<generator object <genexpr> at 0x7fc4f17acc10>

In [14]:
np.fromiter(gen,dtype = int)

array([ 0,  1,  4,  9, 16])

In [18]:
#or
for i in gen:
    print(i)

In [19]:
np.fromstring('1,2,3,4',sep = ',',dtype = int)

array([1, 2, 3, 4])

In [20]:
l = [3,4,5,6,7,8]

In [22]:
arr = np.array(l)

In [28]:
arr1 = np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])

In [24]:
type(arr)

numpy.ndarray

In [27]:
arr.ndim


1

In [29]:
type(arr1)

numpy.ndarray

In [30]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [31]:
arr1.ndim

2

In [32]:
arr1.size

12

In [33]:
arr1.shape

(3, 4)

In [34]:
arr.size

6

In [37]:
arr2 = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])

In [38]:
arr2

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [39]:
arr2.shape # means 2 number of (2,4) data (way of reading)

(2, 2, 4)

In [40]:
arr2.size

16

In [41]:
arr2.ndim

3

In [42]:
# we can also make 4d array

In [46]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [47]:
range(5)

range(0, 5)

In [50]:
list(range(5))

[0, 1, 2, 3, 4]

In [51]:
list(range(6.6)) # range function does not support float numbers so

TypeError: 'float' object cannot be interpreted as an integer

In [52]:
list(np.arange(6.6)) # substitute of rnage function  

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0]

In [55]:
list(np.arange(6.6,20,4)) #(start,end,step)

[6.6, 10.6, 14.6, 18.6]

In [57]:
list(np.arange(6.6,20,-4))

[]

In [58]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
np.arange(1.9,9.9)

array([1.9, 2.9, 3.9, 4.9, 5.9, 6.9, 7.9, 8.9])

In [62]:
np.linspace(3,8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [63]:
np.linspace(1,2,5) # in between a line it will generate data

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [64]:
# start, stop , number of values

In [65]:
np.linspace(.4,.5,3)

array([0.4 , 0.45, 0.5 ])

In [66]:
# generating 5 number between 1 to 10

In [67]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [68]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [70]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [72]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [73]:
np.ones(4)

array([1., 1., 1., 1.])

In [74]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [75]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [76]:
np.ones((2,3,4))+5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [77]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [78]:
np.empty((2,3,4))

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [79]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [80]:
# every output is ndarray

In [81]:
np.eye(2)   # identity  matrix

array([[1., 0.],
       [0., 1.]])

In [83]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [84]:
np.linspace(2,4,4,endpoint = False )# will not include upper bound

array([2. , 2.5, 3. , 3.5])

In [86]:
np.linspace(2,4,4,endpoint = False ,axis = 0)

array([2. , 2.5, 3. , 3.5])

In [87]:
# axis 1 will give error as we dont have column in 1D array

In [91]:
np.linspace([1,6],4,10,endpoint = False ,axis = 1)

array([[1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7],
       [6. , 5.8, 5.6, 5.4, 5.2, 5. , 4.8, 4.6, 4.4, 4.2]])

In [93]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [94]:
np.logspace([2],[3],axis = 0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [95]:
np.logspace([2],[3],axis = 1)

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

In [96]:
d = np.linspace(4,7,40)

In [97]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [98]:
d.shape

(40,)

In [99]:
d.ndim

1

In [100]:
d.reshape(20,2)

array([[4.        , 4.07692308],
       [4.15384615, 4.23076923],
       [4.30769231, 4.38461538],
       [4.46153846, 4.53846154],
       [4.61538462, 4.69230769],
       [4.76923077, 4.84615385],
       [4.92307692, 5.        ],
       [5.07692308, 5.15384615],
       [5.23076923, 5.30769231],
       [5.38461538, 5.46153846],
       [5.53846154, 5.61538462],
       [5.69230769, 5.76923077],
       [5.84615385, 5.92307692],
       [6.        , 6.07692308],
       [6.15384615, 6.23076923],
       [6.30769231, 6.38461538],
       [6.46153846, 6.53846154],
       [6.61538462, 6.69230769],
       [6.76923077, 6.84615385],
       [6.92307692, 7.        ]])

In [101]:
d.reshape(2,10,2)

array([[[4.        , 4.07692308],
        [4.15384615, 4.23076923],
        [4.30769231, 4.38461538],
        [4.46153846, 4.53846154],
        [4.61538462, 4.69230769],
        [4.76923077, 4.84615385],
        [4.92307692, 5.        ],
        [5.07692308, 5.15384615],
        [5.23076923, 5.30769231],
        [5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462],
        [5.69230769, 5.76923077],
        [5.84615385, 5.92307692],
        [6.        , 6.07692308],
        [6.15384615, 6.23076923],
        [6.30769231, 6.38461538],
        [6.46153846, 6.53846154],
        [6.61538462, 6.69230769],
        [6.76923077, 6.84615385],
        [6.92307692, 7.        ]]])

In [102]:
# random data generation

In [106]:
np.random.rand(1,10)

array([[0.36453682, 0.33410739, 0.65527046, 0.48580349, 0.1389594 ,
        0.87096223, 0.50077713, 0.74679363, 0.47811494, 0.99771361]])

In [107]:
np.random.randn(5) # standard normal distribution

array([ 0.40319938,  0.18625728,  0.09355726, -0.91867978,  0.53771881])

In [108]:
np.random.rand(2,3)

array([[0.85764017, 0.35586376, 0.64884438],
       [0.44322406, 0.67043309, 0.49185207]])

In [111]:
np.random.randint(10)

5

In [112]:
np.random.randint(5,50,(4,5))

array([[34, 38, 36, 29, 27],
       [23, 46, 21, 16, 32],
       [33, 45, 21, 10, 27],
       [39, 36, 34, 48, 20]])

In [113]:
arr = np.random.randint(3,9,(3,3))

In [114]:
arr

array([[8, 7, 5],
       [3, 8, 5],
       [3, 3, 8]])

In [115]:
arr.reshape(1,9)

array([[8, 7, 5, 3, 8, 5, 3, 3, 8]])

In [116]:
arr.reshape(9,1)

array([[8],
       [7],
       [5],
       [3],
       [8],
       [5],
       [3],
       [3],
       [8]])

In [117]:
arr.reshape(1,1,9)

array([[[8, 7, 5, 3, 8, 5, 3, 3, 8]]])

In [118]:
arr.reshape(3,-1)

array([[8, 7, 5],
       [3, 8, 5],
       [3, 3, 8]])

In [119]:
arr.reshape(3,-11321) # negative just represent the rest of array

array([[8, 7, 5],
       [3, 8, 5],
       [3, 3, 8]])

In [120]:
arr.reshape(-2378,9)

array([[8, 7, 5, 3, 8, 5, 3, 3, 8]])

In [121]:
arr.max()

8

In [122]:
arr.min()

3

In [125]:
arr = np.random.randint(4,100,(5,5))

In [126]:
arr

array([[79, 72, 22, 44, 93],
       [23, 26,  4, 89, 51],
       [86, 75, 90, 61, 64],
       [50, 25, 21, 92, 71],
       [10, 32, 85,  8, 31]])

In [128]:
arr[3: , 3: ]

array([[92, 71],
       [ 8, 31]])

In [129]:
arr[ : ,[1,3]]

array([[72, 44],
       [26, 89],
       [75, 61],
       [25, 92],
       [32,  8]])

In [130]:
arr > 10

array([[ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True, False,  True]])

In [132]:
arr * arr

array([[6241, 5184,  484, 1936, 8649],
       [ 529,  676,   16, 7921, 2601],
       [7396, 5625, 8100, 3721, 4096],
       [2500,  625,  441, 8464, 5041],
       [ 100, 1024, 7225,   64,  961]])

In [133]:
arr1 = np.random.randint(2,4,(3,3))

In [134]:
arr2 = np.random.randint(2,4,(3,3))

In [135]:
arr1 * arr2

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 4]])

In [136]:
arr1@arr2 # matrix multiplication

array([[21, 19, 16],
       [21, 18, 17],
       [18, 16, 14]])

In [137]:
arr / 0

<ipython-input-137-db39a1c38901>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr / 0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [138]:
arr ** 2

array([[6241, 5184,  484, 1936, 8649],
       [ 529,  676,   16, 7921, 2601],
       [7396, 5625, 8100, 3721, 4096],
       [2500,  625,  441, 8464, 5041],
       [ 100, 1024, 7225,   64,  961]])

In [139]:
# broadcasting

In [141]:
arr = np.zeros((3,4))

In [142]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [143]:
a = np.array([1,2,3,4])

In [144]:
a+arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [150]:
b = np.array([1,2,3])

In [151]:
b.reshape(3,1) + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [152]:
b.T

array([1, 2, 3])

In [153]:
b

array([1, 2, 3])

In [154]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [155]:
arr.T

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [156]:
np.sqrt(arr)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [157]:
np.exp(arr)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [158]:
np.log10(arr)

<ipython-input-158-4473232fb1a0>:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)


array([[-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf]])

In [159]:
arr1 = np.random.randint(2,5,(5,5))

In [160]:
np.log10(arr1)

array([[0.30103   , 0.47712125, 0.30103   , 0.47712125, 0.47712125],
       [0.60205999, 0.47712125, 0.30103   , 0.60205999, 0.60205999],
       [0.47712125, 0.47712125, 0.30103   , 0.60205999, 0.47712125],
       [0.47712125, 0.30103   , 0.30103   , 0.60205999, 0.60205999],
       [0.30103   , 0.60205999, 0.60205999, 0.60205999, 0.47712125]])

In [161]:
np.full((3,3),101)

array([[101, 101, 101],
       [101, 101, 101],
       [101, 101, 101]])

In [162]:
v1 = np.array([1,2,3,4])
v2 = np.array([2,3,4,5])
v3 = np.array([3,4,5,6])

In [163]:
a = np.vstack([v1,v2,v3])

In [164]:
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [165]:
b = np.hstack([v1,v2,v3])

In [166]:
b

array([1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6])